In [95]:
import numpy as np

In [96]:
a = np.array([1, 2, 3])
print(a, ' ', type(a))

[1 2 3]   <class 'numpy.ndarray'>


Срезы

In [97]:
a[:2]

array([1, 2])

In [98]:
a[::2]

array([1, 3])

Многомерные массивы

In [99]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)


[[1. 2. 3.]
 [4. 5. 6.]]


Обращение к элементу двумерного массива

In [100]:
a[1, 2]


6.0

Срезы в двумерном массиве работают a[элемент по которому будет срез, s:s:s]

In [101]:
a[1, ::2]

array([4., 6.])

Шаг 2 по 1 элементу [4, 5, 6]

Методы

In [102]:
a.shape

(2, 3)

Количество строк и столбцов в массиве

In [103]:
a.dtype

dtype('float64')

Тип данных 

In [104]:
len(a)

2

Возвращает длинну оси(количество строк)

In [105]:
6 in a

True

Проверка на вложенность 

Reshape

In [106]:
a = np.array(range(12), float)
a 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [107]:
a = a.reshape((4, 3))
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

Создаем массив от 0 до 12 и с помощью метода reshape делим его на двумерный массив (число строк, число столбцов)

In [108]:
a = np.array([1, 2, 3])
c = a.copy()

In [109]:
a.tolist()

[1, 2, 3]

Преобразование в Python list

In [110]:
a.flatten()

array([1, 2, 3])

Преобразование в одномерный массив

Объединение

In [111]:
np.concatenate((a, c))

array([1, 2, 3, 1, 2, 3])

Если массив не одномерный, можео задать ось по которой будет происходить соединение(по умолчанию по строкам)

In [112]:
np.concatenate((a, c), axis=0) # 1


array([1, 2, 3, 1, 2, 3])

Матан 

In [113]:
print(a + c) # медленно
print(np.add(a, c)) # быстро

[2 4 6]
[2 4 6]


In [114]:
print(a - c) # медленно
print(np.subtract(a, c)) # быстро

[0 0 0]
[0 0 0]


In [115]:
print(a * c) # медленно
print(np.multiply(a, c)) # быстро

[1 4 9]
[1 4 9]


In [116]:
print(a / c) # медленно
print(np.divide(a, c)) # быстро

[1. 1. 1.]
[1. 1. 1.]


In [117]:
print(np.sqrt(a)) # быстро
print(np.sqrt(c)) # быстро

[1.         1.41421356 1.73205081]
[1.         1.41421356 1.73205081]
